///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String splashImage = 'assets/images/splash.png';

  static const String googleIcon = 'assets/images/ic_gg.png';
  static const String eyeIcon = 'assets/images/eye_1.png';
  static const String homeIcon = 'assets/images/home.png';
  static const String bookingIcon = 'assets/images/booking.png';
  static const String routeIcon = 'assets/images/route.png';
  static const String settingIcon = 'assets/images/setting.png';
  static const String historyIcon = 'assets/images/history.png';
  static const String userIcon = 'assets/images/user.png';
  static const String plusCircleIcon = 'assets/images/plus_circle.png';
  static const String departureCircleIcon = 'assets/images/departure_circle.png';
  static const String destinationCircleIcon = 'assets/images/destination_circle.png';
  static const String editIcon = 'assets/images/edit.png';
  static const String trashIcon = 'assets/images/trash.png';
  static const String backIcon = 'assets/images/back.png';
  static const String searchIcon = 'assets/images/search.png';


  static const String emptyImage = 'assets/images/empty.png';
  static const String searchEmptyImage = 'assets/images/search_empty.png';

}
