///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String googleIcon = 'assets/images/ic_gg.png';
  static const String eyeIcon = 'assets/images/eye_1.png';


}
